apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-stable
  namespace: front
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: front
      version: stable
  template:
    metadata:
      labels:
        app: front
        version: stable
    spec:
      containers:
      - name: front
        image: barcino/frontend:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: front-config

---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: front
spec:
  selector:
    app: front
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer

--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-front-stable
  namespace: front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-stable
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50