apiVersion: v1
kind: Namespace
metadata:
  name: todos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
  namespace: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: barcino/todos:1.0.0
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: todos-config
        - secretRef:
            name: todos-secret
---
apiVersion: v1
kind: Service
metadata:
  name: todos-svc
  namespace: todos
spec:
  selector:
    app: todos
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP