apiVersion: v1
kind: Namespace
metadata:
  name: users-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: barcino/users-api:1.0.0
        ports:
        - containerPort: 8083
        env:
        - name: JWT_SECRET
          value: "PRFT"
        - name: SERVER_PORT
          value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-svc
  namespace: users-api
spec:
  selector:
    app: users-api
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
---