apiVersion: v1
kind: Namespace
metadata:
  name: users-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: barcino/users-api:1.0.0
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: users-api-config
        - secretRef:
            name: users-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-svc
  namespace: users-api
spec:
  selector:
    app: users-api
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-users-api
  namespace: users-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50