apiVersion: v1
kind: Namespace
metadata:
  name: auth-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: barcino/auth-api:1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: JWT_SECRET
          value: "PRFT"
        - name: AUTH_API_PORT
          value: "8000"
        - name: USERS_API_ADDRESS
          value: "http://users-api-svc.users-api.svc.cluster.local:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
  namespace: auth-api
spec:
  selector:
    app: auth-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---