apiVersion: v1
kind: Namespace
metadata:
  name: logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs
  namespace: logs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs
          image: barcino/logs:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_HOST
              value: "redis-svc.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"

---
apiVersion: v1
kind: Service
metadata:
  name: logs-svc
  namespace: logs
spec:
  selector:
    app: logs
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP