apiVersion: v1
kind: Namespace
metadata:
  name: todos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
  namespace: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: barcino/todos:1.0.0
        ports:
          - containerPort: 8082
        env:
            - name: TODO_API_PORT
              value: "8082"
            - name: JWT_SECRET
              value: "PRFT"
            - name: REDIS_HOST
              value: "redis-svc.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
---
apiVersion: v1
kind: Service
metadata:
  name: todos-svc
  namespace: todos
spec:
  selector:
    app: todos
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
---