apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-stable
  namespace: front
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: front
      version: stable
  template:
    metadata:
      labels:
        app: front
        version: stable
    spec:
      containers:
      - name: front
        image: barcino/frontend:1.0.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: front-config

---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: front
spec:
  selector:
    app: front
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer