apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: logs-egress-redis
  namespace: logs
spec:
  podSelector:
    matchLabels:
      app: logs
  policyTypes:
  - Ingress
  - Egress
  ingress: [] 
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: redis
      podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53     
    - protocol: TCP
      port: 53
---